version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk-stretch

    working_directory: ~/beeline-java

    environment:
      # Customize the JVM maximum heap limit
      JVM_OPTS: -Xmx3200m
      TERM: dumb

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          key: circleci-demo-java-spring-{{ checksum "pom.xml" }}

      - run: mvn dependency:go-offline # gets the project dependencies

      - save_cache: # saves the project dependencies
          paths:
            - ~/.m2
          key: beeline-java-{{ checksum "pom.xml" }}

      - run: mvn package # run the actual tests
